daemons = [
'Aamon: Demonio asociado al dinero y por eso trae el pecado de la avaricia, dicen que es el regente de Inglaterra.', 
'Belia: Este demonio es asociado con la corrupción y la arrogancia. Dicen que también viaja al lado de Satanás, Lilith y Leviatán.',
'Paimon: Este demonio tiene a su cargo una legión de demonios. Se dice que se puede invocar para responder cualquier pregunta o instruirse en ciencia, filosofía o arte, siempre y cuando estés dispuesto a hacer un sacrificio.',
'Agares: Es conocido como el director de una amplia legión de demonios. Se dice que puede enseñar otras lenguas y estimula el hallar el placer en acciones inmorales.',
'Sidragaso: Este demonio está asociado con la lujuria e incita a los placeres sensuales.',
'Balban: La historia apunta a que Balban es uno de los ángeles caídos encargado de las situaciones de engaño.',
'Baphomet: Este es uno de los demonios más venerados por los templarios. Su naturaleza es difusa, algunos opinan que es un demonio bueno y otros, que es símbolo de maldad.',
'Bael: Él es la cabeza de los poderes infernales.',
'Baalzephon: Es el guardián de los centinelas del infierno y a su vez el Capitán.',
'Baaalberith: Este es un demonio de segundo orden. Es uno de los príncipes más poderosos del infierno, quien antes era un dios de los fenicios.',
'Alouqua: Este demonio femenino se encarga de llevar a los hombres a un cansancio extremo que los pueda llevar hasta el suicidio.', 
'Abrahel: Esta es un demonio femenino considerada como la reina de los súcubos.', 
'Abyzou: Demonio femenino que persigue a las embarazadas.', 
'Aradia: Es un demonio femenino, destacada por ser la hermana de Lucifer.',
'Astartea: Es el ángel femenino del infierno.', 
'Habondia: Ella es la reina de las hadas.',
'Lilith: Ella es la madre de los vampiros. La historia de Lilith dice que ella fue la primera mujer en el Paraíso, acompañó a Adán antes que Eva.',  
'Nahama: Nahama es un demonio femenino. Es la encargada de portar el consuelo.',  
'Noctiluca: Es considerada como la diosa francesa de los vampiros.',  
'Perséfone: Reina y señora del inframundo.',  
'Perisas: Son las hadas de la muerte.',  
'Tamar: Considerada como la Reina del desprecio femenino.', 
'Zalir: Este demonio femenino actúa como la patrona de las lesbianas.', 
'Zemunín: Patrona de las prostitutas.',  
'Asmodeo: Este demonio también se identifica con Samael y se dice que fue la serpiente que sedujo a Eva.', 
'Behemoth: Aparece en La Biblia y es conocido como uno de los demonios más poderosos del infierno. Dicen que él encarna toda la maldad del mundo.', 
'Lucifer: Según la Biblia, Lucifer también llamado Satanás, era el ángel más bello y poderoso. Este se reveló contra Dios y fue derrotado por el Arcángel Miguel. Después de desterrado Lucifer se convierte en el jefe de todos los demonios.',  
'Mammón: Dentro de los nombres de demonios, este es uno de los más antiguos. Cuenta la leyenda que este demonio que es el hijo del gran demonio y representa la codicia, la avaricia y el poder.;',  
'Leviatán: Este es otro de los nombres de demonios más conocidos. Se dice que es un demonio acuático que vive en las profundidades del océano y está acecho de los débiles de espíritu.', 
'Astaroth: Es considerado como uno de los grandes duques del infierno. Dicen que tiene el poder de mostrar los tesoros ocultos, incita a la vanidad y tiene la capacidad de modificar las líneas del destino de cualquier ser terrestre o divino.', 
'Diablo: Comúnmente se le suele llamar Diablo a cualquier representación de Satanás. No obstante, Diablo es un demonio diferente que se unió a la desobediencia frente a Dios.',  
'Baal: Es un rey de los infiernos. Es la divinidad principal de los fenicios, los caldeos y los babilonios. Este demonio reina en oriente.', 
]
